name: Build Windows Server ISO

run-name: >
  ${{ inputs.versions }}
  ${{ inputs.architecture }}
  ${{ inputs.language }}
  ${{ inputs.esd && 'ESD' || '' }}
  ${{ inputs.drivers && 'DRIVERS' || '' }}

on:
  schedule:
    - cron: '30 2 1 * *' # 每月1号自动定时构建
  workflow_dispatch:
    inputs:
      architecture:
        description: "Server architecture"
        type: choice
        options: [x64, arm64]
        default: x64
        required: true
      versions:
        description: "Windows Server version to build"
        type: choice
        options:
          - Windows Server 2025
          - Windows Server 2022
          - Windows Server 2019
        default: Windows Server 2025
        required: true
      edition:
        description: "Server edition"
        type: choice
        options: [standard, datacentre, multi]
        default: multi
        required: true
      language:
        description: "Language"
        type: choice
        options:
          - English (United States)
          - Chinese (Simplified, China)
        default: Chinese (Simplified, China)
        required: true
      esd:
        description: "Use ESD compression"
        type: boolean
        required: true
        default: true
      drivers:
        description: "Add additional drivers (only for x64)"
        type: boolean
        required: true
        default: false

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ fromJSON('{"x64":"windows-2025","arm64":"windows-11-arm"}')[inputs.architecture] }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Map inputs
        id: map
        shell: pwsh
        run: |
          $langMap = @{
            'English (United States)'='en-us'
            'Chinese (Simplified, China)'='zh-cn'
          }

          $verMap = @{
            'Windows Server 2025' = 'windows-server-2025'
            'Windows Server 2022' = 'windows-server-2022'
            'Windows Server 2019' = 'windows-server-2019'
          }

          $langCode = $langMap['${{ inputs.language }}']
          $verCode  = $verMap['${{ inputs.versions }}']

          $opts = ''
          if ('${{ inputs.esd }}' -eq 'true')     { $opts += ' -esd' }
          if (('${{ inputs.drivers }}' -eq 'true') -and ('${{ inputs.architecture }}' -ne 'arm64')) {
            $opts += ' -drivers'
          }
          $opts = $opts.Trim()

          echo "lang=$langCode"    >> $env:GITHUB_OUTPUT
          echo "version=$verCode"  >> $env:GITHUB_OUTPUT
          if ($opts) {
            echo "options=$opts"   >> $env:GITHUB_OUTPUT
          }

      - name: Build Windows Server
        id: build_server
        shell: pwsh
        run: |
          pwsh uup-dump-get-windows-iso.ps1 ${{ steps.map.outputs.version }} ${{ inputs.architecture == 'arm64' && 'c:/output' || 'd:/output' }} -architecture ${{ inputs.architecture }} -edition ${{ inputs.edition }} -lang ${{ steps.map.outputs.lang }} ${{ steps.map.outputs.options }}
          echo "iso_name=$env:ISO_NAME" >> $env:GITHUB_ENV

      - name: Create split zip
        shell: pwsh
        run: |
          7z a -tzip -mx=0 -v1950M -bsp2 "${{ inputs.architecture == 'arm64' && 'c:/output' || 'd:/output' }}/$($env:ISO_NAME).zip" "$((Get-Item -Path '${{ inputs.architecture == 'arm64' && 'C:/output' || 'D:/output' }}/*.ISO').FullName)"

      - name: Upload ISO artifact
        id: upload_iso_artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ISO_NAME }}
          path: ${{ inputs.architecture == 'arm64' && 'c:/output/*.ISO' || 'd:/output/*.ISO' }}
          if-no-files-found: error

      - name: Build summary
        id: build_summary
        shell: pwsh
        run: |
          $iso = Get-Content (Resolve-Path '${{ inputs.architecture == 'arm64' && 'c:/output' || 'd:/output' }}/*.json') | ConvertFrom-Json
          $finalImageName = $iso.images | ForEach-Object { $_.name } -join '/'

          echo "build=$($iso.build)" >> $env:GITHUB_ENV
          echo "version=$($iso.version)" >> $env:GITHUB_ENV
          echo "tagname=server.$($iso.build).${{ inputs.edition }}.${{ inputs.architecture }}.${{ steps.map.outputs.lang }}" >> $env:GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "${{ env.tagname }}"
          name: "Windows Server ${{ inputs.versions }} ${{ inputs.architecture }} (${{ env.build }})"
          files: |
            ${{ inputs.architecture == 'arm64' && 'C:/output/*.zip.0*' || 'D:/output/*.zip.0*' }}